name: 'Clean out Cells,output Jupyter Notebooks EnronRepo'
description: '11-18-24 Updated package for Enforce rules on certain cells and metadata in Jupyter Notebooks'
inputs:
  disable-checks:
    description: 'Olist to check for disable'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'alert-triangle'
  color: 'yellow'
